/**

 * asb_SelectListOverlayConfig

 * Copyright (c) 2013 Salesforce.com.

 * @author fbouchaton@salesforce.com

*/
public class asb_SelectListOverlayConfig {
	
	public String title {get;set;}
	public String description {get;set;}
	public List<SelectOption> selectListValues {get;set;}
	public String valueSelected {get;set;}
	public String errorMessage {get;set;}
	public String saveAction {get;set;}

}